/* !file arm9 */
ChangeGlobalBorderColor = 0x02027A80;
TextboxSolid = 0x0202715C;
TextboxTransparent = 0x02027148;
ResumeAdvancedMenu = 0x0202BBF0;
MyGetPressedButtons = 0x0200625C;
MyGetHeldButtons = 0x020061EC;

/* !file overlay11 */
MenuStartFinish = 0x022e68ac;
MenuEndFinish = 0x022e6e58;
MessageMenuKeyboardEnd = 0x022e6a2c;
StationLoadHangerSSA = 0x022e4c48;
StationLoadHangerSSB = 0x022e57fc;
GetSceneNameCallsite = 0x022debf4;
GetSceneName = 0x022e4600;
